FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["MyApplication/MyApplication.csproj", "MyApplication/" ]
COPY ["MyApplication.Client/MyApplication.Client.csproj", "MyApplication.Client/" ]

RUN dotnet restore "MyApplication/MyApplication.csproj"
COPY . .
WORKDIR "/src/MyApplication"
RUN dotnet publish "MyApplication.csproj" -c release -o /app

FROM base AS final
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT [ "dotnet", "MyApplication.dll" ]